-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'complete'::text CHECK (status = ANY (ARRAY['pending'::text, 'complete'::text, 'error'::text])),
  error_detail text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL DEFAULT 'Nova conversa'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_message_at timestamp with time zone,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.etl_error_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id text NOT NULL,
  script_name text NOT NULL,
  step_name text,
  phase text,
  event_type text NOT NULL,
  severity text NOT NULL DEFAULT 'error'::text,
  table_name text,
  legacy_id text,
  error_class text,
  probable_constraint text,
  message text NOT NULL,
  traceback text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT etl_error_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  saldo numeric NOT NULL DEFAULT 0,
  tipo character varying NOT NULL CHECK (upper(tipo::text) = ANY (ARRAY['PF'::text, 'PJ'::text])),
  telefone character varying,
  celular character varying,
  email_log character varying NOT NULL UNIQUE,
  senha_log character varying,
  ultimo_acesso timestamp without time zone,
  ip character varying,
  status integer NOT NULL DEFAULT 1,
  retirada smallint,
  retirada_limite numeric DEFAULT 0,
  revendedor integer,
  pdv integer,
  wpp_verificado character varying,
  logotipo character varying,
  pagarme_id character varying,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_clientes_enderecos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  titulo character varying,
  cep character varying,
  logradouro character varying,
  numero character varying,
  bairro character varying,
  complemento character varying,
  cidade character varying,
  estado character varying,
  is_principal boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_clientes_enderecos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_clientes_enderecos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
CREATE TABLE public.is_clientes_extratos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  pedido_id uuid,
  pagamento_id uuid,
  saldo_antes numeric NOT NULL,
  saldo_depois numeric NOT NULL,
  descricao character varying,
  obs character varying,
  valor numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT is_clientes_extratos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_clientes_extratos_pagamento_id FOREIGN KEY (pagamento_id) REFERENCES public.is_pedidos_pagamentos(id),
  CONSTRAINT fk_is_clientes_extratos_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id),
  CONSTRAINT fk_is_clientes_extratos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
CREATE TABLE public.is_clientes_pf (
  cliente_id uuid NOT NULL,
  nome character varying CHECK (nome IS NOT NULL),
  sobrenome character varying,
  nascimento timestamp without time zone,
  cpf character varying,
  sexo character varying,
  CONSTRAINT is_clientes_pf_pkey PRIMARY KEY (cliente_id),
  CONSTRAINT fk_is_clientes_pf_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
CREATE TABLE public.is_clientes_pj (
  cliente_id uuid NOT NULL,
  razao_social character varying CHECK (razao_social IS NOT NULL),
  fantasia character varying,
  ie character varying,
  cnpj character varying,
  CONSTRAINT is_clientes_pj_pkey PRIMARY KEY (cliente_id),
  CONSTRAINT fk_is_clientes_pj_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
CREATE TABLE public.is_entregas_balcoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titulo character varying NOT NULL,
  telefone character varying,
  logradouro character varying,
  cep character varying,
  complemento character varying,
  bairro character varying,
  cidade character varying,
  estado character varying,
  custo numeric NOT NULL CHECK (custo >= 0::numeric),
  prazo character varying,
  created_at timestamp without time zone DEFAULT now(),
  arquivado boolean DEFAULT false,
  CONSTRAINT is_entregas_balcoes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_entregas_fretes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  titulo character varying NOT NULL,
  descricao character varying,
  prazo integer,
  min_km character varying,
  max_km character varying,
  taxa numeric NOT NULL,
  min_compra numeric NOT NULL DEFAULT 0,
  tipo integer NOT NULL,
  minimo_peso character varying,
  limite_peso character varying,
  minimo_c integer,
  limite_c integer,
  CONSTRAINT is_entregas_fretes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_entregas_fretes_locais (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  frete_id uuid NOT NULL,
  estado character varying,
  cidade character varying,
  bairro character varying,
  cep_inicio character varying,
  cep_fim character varying,
  CONSTRAINT is_entregas_fretes_locais_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_entregas_fretes_locais_frete_id FOREIGN KEY (frete_id) REFERENCES public.is_entregas_fretes(id)
);
CREATE TABLE public.is_extras_status (
  id integer NOT NULL,
  nome character varying NOT NULL,
  num integer,
  visivel integer,
  CONSTRAINT is_extras_status_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_financeiro_funcionarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  nome character varying NOT NULL,
  sobrenome character varying,
  nascimento timestamp without time zone,
  cpf character varying,
  rg character varying,
  sexo character varying,
  telefone character varying,
  celular character varying,
  cep character varying,
  logradouro character varying,
  numero character varying,
  bairro character varying,
  complemento character varying,
  cidade character varying,
  estado character varying,
  admissao date,
  demissao date,
  salario numeric NOT NULL,
  salario_vencimento integer,
  vale numeric DEFAULT 0,
  vale_vencimento integer,
  cargo character varying,
  obs text,
  CONSTRAINT is_financeiro_funcionarios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_financeiro_lancamentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  descricao character varying,
  valor numeric NOT NULL CHECK (valor >= 0::numeric),
  data timestamp without time zone,
  data_pagto timestamp without time zone,
  data_emissao timestamp without time zone,
  categoria_id uuid,
  obs text,
  anexo character varying,
  anexo_arquivo_id uuid,
  carteira_id uuid,
  tipo integer NOT NULL CHECK (tipo = ANY (ARRAY[1, 2])),
  status integer NOT NULL,
  fornecedor_id uuid,
  pdv_id uuid,
  funcionario_id uuid,
  vendedor_id uuid,
  caixa_id uuid,
  centro_custo_id uuid,
  origem integer,
  uid character varying,
  agrupar integer,
  conciliacao character varying,
  conciliacao_movimentacao integer,
  conciliacao_pagto integer,
  neutro integer,
  repetir integer,
  CONSTRAINT is_financeiro_lancamentos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_financeiro_lancamentos_funcionario_id FOREIGN KEY (funcionario_id) REFERENCES public.is_financeiro_funcionarios(id),
  CONSTRAINT fk_is_financeiro_lancamentos_vendedor_id FOREIGN KEY (vendedor_id) REFERENCES public.is_usuarios(id)
);
CREATE TABLE public.is_mkt_cupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  codigo character varying NOT NULL UNIQUE,
  tipo character varying NOT NULL CHECK (lower(tipo::text) = ANY (ARRAY['percent'::text, 'amount'::text])),
  valor numeric NOT NULL CHECK (valor >= 0::numeric),
  uso integer NOT NULL DEFAULT 0,
  limite integer,
  inicio timestamp without time zone,
  fim timestamp without time zone,
  pedido_min numeric NOT NULL DEFAULT 0,
  primeira_compra boolean NOT NULL DEFAULT false,
  arquivado boolean NOT NULL DEFAULT false,
  CONSTRAINT is_mkt_cupons_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_mkt_cupons_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
CREATE TABLE public.is_mkt_cupons_produtos (
  cupom_id uuid NOT NULL,
  produto_id uuid NOT NULL,
  CONSTRAINT is_mkt_cupons_produtos_pkey PRIMARY KEY (cupom_id, produto_id),
  CONSTRAINT fk_is_mkt_cupons_produtos_cupom_id FOREIGN KEY (cupom_id) REFERENCES public.is_mkt_cupons(id),
  CONSTRAINT fk_is_mkt_cupons_produtos_produto_id FOREIGN KEY (produto_id) REFERENCES public.is_produtos(id)
);
CREATE TABLE public.is_mkt_regras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  desconto numeric NOT NULL,
  regra character varying NOT NULL,
  uso integer NOT NULL DEFAULT 0,
  tipo integer NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_mkt_regras_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_pedidos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  cliente_id uuid NOT NULL,
  usuario_id uuid,
  total numeric NOT NULL,
  acrescimo numeric NOT NULL DEFAULT 0,
  desconto numeric NOT NULL DEFAULT 0,
  desconto_uso numeric NOT NULL DEFAULT 0,
  sinal numeric NOT NULL DEFAULT 0,
  frete_valor numeric NOT NULL DEFAULT 0,
  frete_tipo character varying,
  frete_rastreio character varying,
  frete_balcao_id uuid,
  frete_endereco_id uuid,
  origem integer,
  obs text,
  obs_interna text,
  nf text,
  cupom character varying,
  json text,
  pdv_id uuid,
  caixa_id uuid,
  devolucao_completa boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_pedidos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id),
  CONSTRAINT fk_is_pedidos_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id),
  CONSTRAINT fk_is_pedidos_frete_balcao_id FOREIGN KEY (frete_balcao_id) REFERENCES public.is_entregas_balcoes(id),
  CONSTRAINT fk_is_pedidos_frete_endereco_id FOREIGN KEY (frete_endereco_id) REFERENCES public.is_clientes_enderecos(id),
  CONSTRAINT fk_is_pedidos_cupom_codigo FOREIGN KEY (cupom) REFERENCES public.is_mkt_cupons(codigo)
);
CREATE TABLE public.is_pedidos_fretes_detalhes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL,
  endereco_json jsonb,
  conteudo_json jsonb,
  CONSTRAINT is_pedidos_fretes_detalhes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_fretes_detalhes_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id)
);
CREATE TABLE public.is_pedidos_fretes_entregas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL,
  envio_id uuid UNIQUE,
  metodo_titulo text,
  modulo text,
  prazo_dias integer,
  valor numeric,
  sucesso boolean,
  hash text,
  descricao text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT is_pedidos_fretes_entregas_pkey PRIMARY KEY (id),
  CONSTRAINT fk_entregas_pedido FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id)
);
CREATE TABLE public.is_pedidos_historico (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  pedido_id uuid,
  item_id uuid,
  status_id integer,
  usuario_id uuid,
  obs character varying,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_pedidos_historico_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_historico_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id),
  CONSTRAINT fk_is_pedidos_historico_item_id FOREIGN KEY (item_id) REFERENCES public.is_pedidos_itens(id),
  CONSTRAINT fk_is_pedidos_historico_status_id FOREIGN KEY (status_id) REFERENCES public.is_extras_status(id),
  CONSTRAINT fk_is_pedidos_historico_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id)
);
CREATE TABLE public.is_pedidos_itens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  pedido_id uuid NOT NULL,
  produto_id uuid,
  descricao character varying,
  status character varying,
  qtde numeric,
  valor numeric,
  arte_valor numeric NOT NULL DEFAULT 0,
  arte_tipo character varying,
  arte_status integer,
  arte_arquivo character varying,
  arte_data timestamp without time zone,
  arte_nome character varying,
  pago boolean NOT NULL DEFAULT false,
  rastreio character varying,
  previsao_producao timestamp without time zone,
  previsao_entrega timestamp without time zone,
  previa character varying,
  origem integer,
  arquivado boolean NOT NULL DEFAULT false,
  data_modificado timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  ftp character varying,
  produto_detalhes text,
  formato character varying,
  formato_detalhes text,
  visto integer,
  vars_raw character varying,
  vars_detalhes text,
  json text,
  categoria integer,
  revendedor integer,
  CONSTRAINT is_pedidos_itens_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_itens_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id),
  CONSTRAINT fk_is_pedidos_itens_produto_id FOREIGN KEY (produto_id) REFERENCES public.is_produtos(id)
);
CREATE TABLE public.is_pedidos_itens_reprovados (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid,
  motivo text NOT NULL,
  usuario_id uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_pedidos_itens_reprovados_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_itens_reprovados_item_id FOREIGN KEY (item_id) REFERENCES public.is_pedidos_itens(id),
  CONSTRAINT fk_is_pedidos_itens_reprovados_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id)
);
CREATE TABLE public.is_pedidos_pag_reprovados (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  comprovante_id uuid,
  motivo text NOT NULL,
  usuario_id uuid,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_pedidos_pag_reprovados_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_pag_reprovados_comprovante_id FOREIGN KEY (comprovante_id) REFERENCES public.is_pedidos_pagamentos(id),
  CONSTRAINT fk_is_pedidos_pag_reprovados_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id)
);
CREATE TABLE public.is_pedidos_pagamentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  cliente_id uuid NOT NULL,
  pedido_id uuid,
  forma character varying NOT NULL,
  condicao character varying,
  valor numeric NOT NULL,
  status integer NOT NULL,
  link character varying,
  visto boolean NOT NULL DEFAULT false,
  saldo_anterior numeric,
  saldo_atual numeric,
  usuario_id uuid,
  obs text,
  uid character varying,
  oculto boolean NOT NULL DEFAULT false,
  pdv_id uuid,
  caixa_id uuid,
  original_id uuid,
  bandeira character varying,
  parcelas_raw character varying,
  parcelas_qtd integer CHECK (parcelas_qtd IS NULL OR parcelas_qtd >= 1),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT is_pedidos_pagamentos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_pedidos_pagamentos_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id),
  CONSTRAINT fk_is_pedidos_pagamentos_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.is_pedidos(id),
  CONSTRAINT fk_is_pedidos_pagamentos_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id),
  CONSTRAINT fk_is_pedidos_pagamentos_original_id FOREIGN KEY (original_id) REFERENCES public.is_pedidos_pagamentos(id)
);
CREATE TABLE public.is_producao_setores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  status character varying,
  CONSTRAINT is_producao_setores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_produtos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  erp_id bigint,
  url character varying,
  titulo character varying NOT NULL,
  sku character varying,
  gtin character varying,
  mpn character varying,
  ncm character varying,
  descricao_curta character varying,
  descricao_html text,
  meta_title character varying,
  meta_description character varying,
  valor_arte numeric NOT NULL DEFAULT 0,
  visivel boolean NOT NULL DEFAULT true,
  arte boolean NOT NULL DEFAULT false,
  vendidos integer NOT NULL DEFAULT 0,
  estoque_controlar boolean NOT NULL DEFAULT false,
  estoque_qtde integer NOT NULL DEFAULT 0,
  estoque_condicao character varying,
  oferta_expira date,
  oferta_condicao character varying,
  mostrar character varying,
  entrega character varying,
  arquivado boolean NOT NULL DEFAULT false,
  video character varying,
  categoria_relatorio integer,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  gabarito character varying,
  material character varying,
  revestimento character varying,
  acabamento character varying,
  extras character varying,
  formato character varying,
  prazo character varying,
  cores character varying,
  selo character varying,
  valor character varying,
  redirect_301 character varying,
  brdraw text,
  revenda_tipo integer,
  revenda_desconto numeric,
  vars_select integer,
  vars_obrig boolean,
  vars_agrupadas integer,
  vars_combinacao integer,
  CONSTRAINT is_produtos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_produtos_categorias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_id uuid,
  slug character varying UNIQUE,
  chave character varying,
  titulo character varying NOT NULL,
  title character varying,
  description character varying,
  descricao text,
  status integer NOT NULL DEFAULT 1,
  CONSTRAINT is_produtos_categorias_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_produtos_categorias_parent_id FOREIGN KEY (parent_id) REFERENCES public.is_produtos_categorias(id)
);
CREATE TABLE public.is_produtos_categorias_extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  produto_id uuid NOT NULL,
  categoria character varying,
  subcategoria character varying,
  secao character varying,
  subsecao character varying,
  subsubsecao character varying,
  CONSTRAINT is_produtos_categorias_extras_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_produtos_categorias_extras_produto_id FOREIGN KEY (produto_id) REFERENCES public.is_produtos(id)
);
CREATE TABLE public.is_produtos_vars (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  produto_id uuid,
  grupo_id uuid,
  opcao character varying NOT NULL,
  nome character varying,
  valor numeric DEFAULT 0,
  estoque integer DEFAULT 0,
  cobranca integer,
  foto character varying,
  cobranca_val integer,
  CONSTRAINT is_produtos_vars_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_produtos_vars_produto_id FOREIGN KEY (produto_id) REFERENCES public.is_produtos(id),
  CONSTRAINT fk_is_produtos_vars_grupo_id FOREIGN KEY (grupo_id) REFERENCES public.is_produtos_vars_nomes(id)
);
CREATE TABLE public.is_produtos_vars_nomes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome character varying NOT NULL,
  texto_exibicao character varying,
  CONSTRAINT is_produtos_vars_nomes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.is_usuarios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  foto character varying,
  nome character varying NOT NULL,
  sobrenome character varying,
  email_log character varying NOT NULL UNIQUE,
  senha_log character varying NOT NULL,
  acesso integer NOT NULL,
  hora_de character varying,
  hora_ate character varying,
  status integer NOT NULL DEFAULT 1,
  ultimo_acesso timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  balcao_id uuid,
  pdv_id uuid,
  comissao_tipo integer,
  comissao_valor integer,
  CONSTRAINT is_usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_usuarios_balcao_id FOREIGN KEY (balcao_id) REFERENCES public.is_entregas_balcoes(id)
);
CREATE TABLE public.is_usuarios_historico (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  usuario_id uuid,
  cliente_id uuid,
  acao text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT is_usuarios_historico_pkey PRIMARY KEY (id),
  CONSTRAINT fk_is_usuarios_historico_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.is_usuarios(id),
  CONSTRAINT fk_is_usuarios_historico_cliente_id FOREIGN KEY (cliente_id) REFERENCES public.is_clientes(id)
);
